import { useState } from 'react';
import { useQuery, useQueryClient } from '@tanstack/react-query';
import axios, { AxiosError } from 'axios';
import { toast } from 'react-toastify';
import { type SeasonRecord } from './useSeasons';
import { type GroupTeamRecord } from './useLeagueGroups';

const API = import.meta.env.VITE_API_URL || '/api';

const authHeaders = () => ({
  Authorization: `Bearer ${localStorage.getItem('token')}`,
});

const apiError = (err: unknown, fallback: string): string =>
  (err as AxiosError<{ error: string }>).response?.data?.error ?? fallback;

// ── Types ─────────────────────────────────────────────────────────────────────

export interface SeasonGroupRecord {
  id: string;
  league_id: string;
  parent_id: string | null;
  name: string;
  sort_order: number;
  created_at: string;
  teams: GroupTeamRecord[];
  /** True when this group has season-specific team overrides (vs. league defaults). */
  has_season_override: boolean;
  /** true when teams came from the previous season (no explicit override for this season) */
  is_inherited: boolean;
  /** true when this group is auto-generated by the system (not user-created) */
  is_auto: boolean;
}

/** Minimal team shape returned by the league endpoint — used for pickers. */
export interface LeagueTeam {
  id: string;
  name: string;
  code: string;
  logo: string | null;
}

/** Team record returned by the season teams endpoint. */
export interface SeasonTeam extends LeagueTeam {
  primary_color: string;
  text_color: string;
  secondary_color: string;
  /** true when the team was inherited from the previous season (not explicitly set for this one) */
  inherited: boolean;
}

// ── Hook ──────────────────────────────────────────────────────────────────────

const useSeasonDetails = (seasonId: string | undefined) => {
  const queryClient = useQueryClient();
  const [busy, setBusy] = useState<string | null>(null);
  const [groupBusy, setGroupBusy] = useState<string | null>(null);

  // ① Season info (includes league_name, league_code, league_logo)
  const { data: season = null, isLoading: seasonLoading } = useQuery<SeasonRecord | null>({
    queryKey: ['season', seasonId],
    queryFn: async () => {
      try {
        const { data } = await axios.get<SeasonRecord>(
          `${API}/admin/seasons/${seasonId}`,
          { headers: authHeaders() },
        );
        return data;
      } catch (err) {
        toast.error(apiError(err, 'Failed to load season'));
        return null;
      }
    },
    enabled: !!seasonId,
  });

  // ② Season-resolved groups (override OR default teams per group)
  const { data: groups = [], isLoading: groupsLoading } = useQuery<SeasonGroupRecord[]>({
    queryKey: ['season-groups', seasonId],
    queryFn: async () => {
      try {
        const { data } = await axios.get<SeasonGroupRecord[]>(
          `${API}/admin/seasons/${seasonId}/groups`,
          { headers: authHeaders() },
        );
        return data;
      } catch (err) {
        toast.error(apiError(err, 'Failed to load season groups'));
        return [];
      }
    },
    enabled: !!seasonId,
  });

  // ③ All league teams — used to populate the override modal
  const leagueId = season?.league_id;
  const { data: leagueData = null, isLoading: leagueLoading } = useQuery<{ teams: LeagueTeam[] } | null>({
    queryKey: ['leagues', leagueId],
    queryFn: async () => {
      try {
        const { data } = await axios.get<{ teams: LeagueTeam[] }>(
          `${API}/admin/leagues/${leagueId}`,
          { headers: authHeaders() },
        );
        return data;
      } catch (err) {
        toast.error(apiError(err, 'Failed to load league'));
        return null;
      }
    },
    enabled: !!leagueId,
  });

  // ④ Teams participating in this season
  const { data: seasonTeams = [], isLoading: seasonTeamsLoading } = useQuery<SeasonTeam[]>({
    queryKey: ['season-teams', seasonId],
    queryFn: async () => {
      try {
        const { data } = await axios.get<SeasonTeam[]>(
          `${API}/admin/seasons/${seasonId}/teams`,
          { headers: authHeaders() },
        );
        return data;
      } catch (err) {
        toast.error(apiError(err, 'Failed to load season teams'));
        return [];
      }
    },
    enabled: !!seasonId,
  });

  const leagueTeams: LeagueTeam[] = leagueData?.teams ?? [];
  const loading =
    seasonLoading || groupsLoading || (!!leagueId && leagueLoading) || seasonTeamsLoading;

  // ── Mutations ────────────────────────────────────────────────────────────────

  const setSeasonTeams = async (teamIds: string[]): Promise<boolean> => {
    setBusy('season-teams');
    try {
      await axios.put(
        `${API}/admin/seasons/${seasonId}/teams`,
        { team_ids: teamIds },
        { headers: authHeaders() },
      );
      toast.success('Season roster updated!');
      await queryClient.invalidateQueries({ queryKey: ['season-teams', seasonId] });
      await queryClient.invalidateQueries({ queryKey: ['season-groups', seasonId] });
      return true;
    } catch (err) {
      toast.error(apiError(err, 'Failed to update season roster'));
      return false;
    } finally {
      setBusy(null);
    }
  };

  const setSeasonGroupTeams = async (groupId: string, teamIds: string[]): Promise<boolean> => {
    setBusy(groupId);
    try {
      await axios.put(
        `${API}/admin/seasons/${seasonId}/groups/${groupId}/teams`,
        { team_ids: teamIds },
        { headers: authHeaders() },
      );
      toast.success('Season teams updated!');
      await queryClient.invalidateQueries({ queryKey: ['season-groups', seasonId] });
      return true;
    } catch (err) {
      toast.error(apiError(err, 'Failed to update season teams'));
      return false;
    } finally {
      setBusy(null);
    }
  };

  const resetSeasonGroupTeams = async (groupId: string): Promise<boolean> => {
    setBusy(groupId);
    try {
      await axios.delete(
        `${API}/admin/seasons/${seasonId}/groups/${groupId}/teams`,
        { headers: authHeaders() },
      );
      toast.success('Reverted to default teams');
      await queryClient.invalidateQueries({ queryKey: ['season-groups', seasonId] });
      return true;
    } catch (err) {
      toast.error(apiError(err, 'Failed to reset season teams'));
      return false;
    } finally {
      setBusy(null);
    }
  };

  // ── Group CRUD ───────────────────────────────────────────────────────────────
  // Groups are league-level entities. Creating / renaming / deleting them here
  // invalidates both the season-groups view and the league groups cache so
  // navigating back to the league page shows fresh data.

  const invalidateGroups = async () => {
    await Promise.all([
      queryClient.invalidateQueries({ queryKey: ['season-groups', seasonId] }),
      queryClient.invalidateQueries({ queryKey: ['groups', season?.league_id] }),
    ]);
  };

  const addGroup = async (data: { name: string; parent_id?: string | null }): Promise<boolean> => {
    if (!season?.league_id) return false;
    try {
      await axios.post(
        `${API}/admin/groups`,
        { ...data, league_id: season.league_id },
        { headers: authHeaders() },
      );
      toast.success('Group created!');
      await invalidateGroups();
      return true;
    } catch (err) {
      toast.error(apiError(err, 'Failed to create group'));
      return false;
    }
  };

  const updateGroup = async (groupId: string, payload: { name: string }): Promise<boolean> => {
    setGroupBusy(groupId);
    try {
      await axios.patch(`${API}/admin/groups/${groupId}`, payload, { headers: authHeaders() });
      toast.success('Group updated!');
      await invalidateGroups();
      return true;
    } catch (err) {
      toast.error(apiError(err, 'Failed to update group'));
      return false;
    } finally {
      setGroupBusy(null);
    }
  };

  const deleteGroup = async (groupId: string): Promise<boolean> => {
    setGroupBusy(groupId);
    try {
      await axios.delete(`${API}/admin/groups/${groupId}`, { headers: authHeaders() });
      toast.success('Group deleted');
      await invalidateGroups();
      return true;
    } catch (err) {
      toast.error(apiError(err, 'Failed to delete group'));
      return false;
    } finally {
      setGroupBusy(null);
    }
  };

  return {
    season,
    groups,
    seasonTeams,
    leagueTeams,
    loading,
    busy,
    groupBusy,
    setSeasonTeams,
    setSeasonGroupTeams,
    resetSeasonGroupTeams,
    addGroup,
    updateGroup,
    deleteGroup,
  };
};

export default useSeasonDetails;
